2024-10-20T10:14:25.417005+00:00 heroku[web.1]: State changed from starting to up
2024-10-20T10:14:28.715859+00:00 app[web.1]: [2024-10-20 10:14:28,715] ERROR in app: Exception on / [GET]
2024-10-20T10:14:28.715872+00:00 app[web.1]: Traceback (most recent call last):
2024-10-20T10:14:28.715872+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
2024-10-20T10:14:28.715873+00:00 app[web.1]: response = self.full_dispatch_request()
2024-10-20T10:14:28.715873+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
2024-10-20T10:14:28.715873+00:00 app[web.1]: rv = self.handle_user_exception(e)
2024-10-20T10:14:28.715879+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
2024-10-20T10:14:28.715882+00:00 app[web.1]: rv = self.dispatch_request()
2024-10-20T10:14:28.715882+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
2024-10-20T10:14:28.715882+00:00 app[web.1]: return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
2024-10-20T10:14:28.715883+00:00 app[web.1]: File "/app/app.py", line 70, in index
2024-10-20T10:14:28.715883+00:00 app[web.1]: driver = init_driver()
2024-10-20T10:14:28.715883+00:00 app[web.1]: File "/app/app.py", line 26, in init_driver
2024-10-20T10:14:28.715884+00:00 app[web.1]: return webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
2024-10-20T10:14:28.715884+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
2024-10-20T10:14:28.715885+00:00 app[web.1]: super().__init__(
2024-10-20T10:14:28.715885+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
2024-10-20T10:14:28.715886+00:00 app[web.1]: super().__init__(command_executor=executor, options=options)
2024-10-20T10:14:28.715886+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 212, in __init__
2024-10-20T10:14:28.715886+00:00 app[web.1]: self.start_session(capabilities)
2024-10-20T10:14:28.715886+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 299, in start_session
2024-10-20T10:14:28.715887+00:00 app[web.1]: response = self.execute(Command.NEW_SESSION, caps)["value"]
2024-10-20T10:14:28.715887+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in execute
2024-10-20T10:14:28.715888+00:00 app[web.1]: self.error_handler.check_response(response)
2024-10-20T10:14:28.715888+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
2024-10-20T10:14:28.715889+00:00 app[web.1]: raise exception_class(message, screen, stacktrace)
2024-10-20T10:14:28.715889+00:00 app[web.1]: selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
2024-10-20T10:14:28.715889+00:00 app[web.1]: Stacktrace:
2024-10-20T10:14:28.716467+00:00 app[web.1]: 10.1.51.24 - - [20/Oct/2024:10:14:28 +0000] "GET / HTTP/1.1" 500 265 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"
2024-10-20T10:14:28.716774+00:00 heroku[router]: at=info method=GET path="/" host=young-retreat-25613-fc689ce72853.herokuapp.com request_id=a63f826a-cca3-413e-9f0d-9d8f8b13f35f fwd="91.160.80.175" dyno=web.1 connect=0ms service=264ms status=500 bytes=438 protocol=https
2024-10-20T10:14:53.000000+00:00 app[api]: Build succeeded
2024-10-20T10:15:02.496557+00:00 app[web.1]: [2024-10-20 10:15:02,491] ERROR in app: Exception on / [GET]
2024-10-20T10:15:02.496568+00:00 app[web.1]: Traceback (most recent call last):
2024-10-20T10:15:02.496569+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
2024-10-20T10:15:02.496569+00:00 app[web.1]: response = self.full_dispatch_request()
2024-10-20T10:15:02.496570+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
2024-10-20T10:15:02.496570+00:00 app[web.1]: rv = self.handle_user_exception(e)
2024-10-20T10:15:02.496571+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
2024-10-20T10:15:02.496571+00:00 app[web.1]: rv = self.dispatch_request()
2024-10-20T10:15:02.496571+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
2024-10-20T10:15:02.496572+00:00 app[web.1]: return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
2024-10-20T10:15:02.496572+00:00 app[web.1]: File "/app/app.py", line 70, in index
2024-10-20T10:15:02.496573+00:00 app[web.1]: driver = init_driver()
2024-10-20T10:15:02.496573+00:00 app[web.1]: File "/app/app.py", line 26, in init_driver
2024-10-20T10:15:02.496573+00:00 app[web.1]: return webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
2024-10-20T10:15:02.496575+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
2024-10-20T10:15:02.496589+00:00 app[web.1]: super().__init__(
2024-10-20T10:15:02.496589+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
2024-10-20T10:15:02.496591+00:00 app[web.1]: super().__init__(command_executor=executor, options=options)
2024-10-20T10:15:02.496591+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 212, in __init__
2024-10-20T10:15:02.496591+00:00 app[web.1]: self.start_session(capabilities)
2024-10-20T10:15:02.496591+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 299, in start_session
2024-10-20T10:15:02.496592+00:00 app[web.1]: response = self.execute(Command.NEW_SESSION, caps)["value"]
2024-10-20T10:15:02.496592+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in execute
2024-10-20T10:15:02.496592+00:00 app[web.1]: self.error_handler.check_response(response)
2024-10-20T10:15:02.496593+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
2024-10-20T10:15:02.496594+00:00 app[web.1]: raise exception_class(message, screen, stacktrace)
2024-10-20T10:15:02.496594+00:00 app[web.1]: selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
2024-10-20T10:15:02.496595+00:00 app[web.1]: Stacktrace:
2024-10-20T10:15:02.496612+00:00 app[web.1]: 10.1.51.24 - - [20/Oct/2024:10:15:02 +0000] "GET / HTTP/1.1" 500 265 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"
2024-10-20T10:15:02.496688+00:00 heroku[router]: at=info method=GET path="/" host=young-retreat-25613-fc689ce72853.herokuapp.com request_id=0e351793-447c-4793-a0d2-08bc5f133546 fwd="91.160.80.175" dyno=web.1 connect=0ms service=439ms status=500 bytes=438 protocol=https
